export const CLASS_CODES = [
  "Accounting",
  "Agricultural Machinery & Equipment",
  "Agricultural Operations",
  "Agriculture",
  "Air conditioning",
  "Alarm & Security System",
  "Ambulance Equipment",
  "Animal Shelters",
  "Appliance Install and Repair",
  "Appliance Installation - commercial",
  "Appliance Installation - residential",
  "Artist",
  "ATM Machines",
  "Auto - Mobile Dent Removal",
  "Auto - Mobile Glass Repair",
  "Auto Detailing",
  "Auto Mechanics Tools / Mobile Mechanic",
  "Auto Paint Booths",
  "Auto Wrapping",
  "Band - Other Portable Personal Property & Equipment",
  "Beautician Equipment",
  "Boat - Mobile Detailing",
  "Boiler Inspection, Installation, Cleaning or Repair, Steam Pipe or Boiler Insulation",
  "Bookkeepers",
  "Brewery Equipment",
  "Building Inspector (Commercial & Residential)",
  "Building Inspector (Commercial)",
  "Building Inspector (Residential)",
  "Cabinet Manufacturer",
  "Carpentry - Commercial",
  "Carpentry - Framing",
  "Carpentry - Handyman",
  "Carpentry - Homebuilder",
  "Carpentry - Interior",
  "Carpentry - Residential",
  "Carpentry - Shop Only",
  "Carpet Cleaning",
  "Carpet Rug, Upholstery cleaning",
  "Caterers",
  "Catering Equipment",
  "Ceiling / Wall Installation - Metal",
  "Chimney Cleaning",
  "Communication Equipment Installation",
  "Concrete Construction",
  "Conduit Construction - Cable / Wire",
  "Consultants",
  "Custom Harvesting",
  "Custom Harvesting Contractor",
  "Dance Studio Equipment",
  "Debris Removal - Construction Site",
  "Demolition - Contractors",
  "Dj Equipment",
  "Dog Daycare & Boarding Facility",
  "Dog Trainers",
  "Dog Walker",
  "Door / Millwork Installation",
  "Dumpster Rentals",
  "Electrical - Within Buildings",
  "Electrical Apparatus - Outside Buildings",
  "Elevator or Escalator Inspecting",
  "Event Planners",
  "Event Venues",
  "Excavation",
  "Farmer",
  "Fence Installation",
  "Financial Advisor",
  "Fire Sprinkler Installation & Service",
  "Flooring Installation",
  "Food Truck Equipment",
  "Framing - Commercial",
  "Framing - Residential",
  "Furniture Manufacturing",
  "Garage Door Install",
  "General Contractor - Commercial",
  "General Contractor - Residential",
  "Glass Installation - Building",
  "Grading",
  "Gutter Installation",
  "Handyman",
  "Hardscaping",
  "HVAC - No LPG",
  "HVAC - With LPG",
  "Insulation Installation",
  "Interior Designer",
  "Janitorial Services",
  "Landscaping",
  "Lawn Care",
  "Locksmith",
  "Machine Shop",
  "Masonry",
  "Painting - Commercial",
  "Painting - Residential",
  "Paving",
  "Pest Control",
  "Photography Studio",
  "Plumbing - Commercial",
  "Plumbing - Residential",
  "Pool Installation",
  "Pressure Washing",
  "Property Manager",
  "Real Estate Agent",
  "Restaurant Equipment",
  "Roofing - Commercial",
  "Roofing - Residential",
  "Sign Installation",
  "Snow Removal",
  "Solar Installation",
  "Stucco",
  "Surveyor",
  "Tile Installation",
  "Tree Trimming",
  "Upholstery",
  "Wallpaper Installation",
  "Welding",
  "Window Installation",
  "Woodworking",
];
